services:
    mikrotik-dhcpdns:
        ports:
            - 5001:5001
        restart: always
        build:
            context: .
        env_file:
            -   .env
        container_name: mikrotik-dhcpdns
        image: mikrotik-dhcpdns
